<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AvtoBus.Abstractions\AvtoBus.Abstractions.csproj" />
    <ProjectReference Include="..\AvtoBus.Core\AvtoBus.Core.csproj" />
  </ItemGroup>
</Project>
