using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace AvtoBus.Generators;

/// <summary>
/// Эмиттеры: диспетчеры для методов и IConsumer&lt;T&gt;, регистрация.
/// Сгенерированный код подключается к текущему рантайму через <c>AvtoBusRegistry</c> и
/// <see cref="AvtoBus.Handlers.IMessageDispatcher"/> — без изменения контрактов ядра.
/// </summary>
internal static class Emitters
{
    private const string DispatcherInterface = "global::AvtoBus.Handlers.IMessageDispatcher";

    public static void EmitDispatcher(SourceProductionContext spc, HandlerInfo h, Compilation compilation)
    {
        var className = ClassNameFor(h.ContainingType, h.MessageClrType);
        var isInstance = !h.IsStatic;
        var fullQualifiedMsgType = h.MessageClrType;

        var call = BuildCall(h, isInstance);
        var awaitPrefix = h.IsAsync ? "await " : "";

        // Зависимости резолвятся из scoped-контейнера; CancellationToken — из контекста.
        var dependencyLines = new StringBuilder();
        foreach (var dep in h.Dependencies)
        {
            var typeName = dep.TypeName;
            if (typeName.StartsWith("global::", StringComparison.Ordinal))
                typeName = typeName.Substring("global::".Length);

            if (typeName is "System.Threading.CancellationToken")
            {
                dependencyLines.AppendLine($"                    var __d_{dep.ParamName} = ctx.CancellationToken;");
            }
            else if (typeName is "AvtoBus.ConsumeContext")
            {
                dependencyLines.AppendLine($"                    var __d_{dep.ParamName} = ctx;");
            }
            else if (typeName is "System.IServiceProvider")
            {
                dependencyLines.AppendLine($"                    var __d_{dep.ParamName} = ctx.Services;");
            }
            else if (typeName is "AvtoBus.Envelope")
            {
                dependencyLines.AppendLine($"                    var __d_{dep.ParamName} = ctx.Envelope;");
            }
            else
            {
                dependencyLines.AppendLine($"                    var __d_{dep.ParamName} = ctx.Services.GetRequiredService<{dep.TypeName}>();");
            }
        }

        // Тело: вызов + разбор результата в каскады через HandlerResult (идея 2).
        var body = h.ReturnKind switch
        {
            ReturnKind.Void => $"{call};",
            ReturnKind.AwaitVoid => $"{awaitPrefix}{call};",
            ReturnKind.AwaitValue => $"var __result = {awaitPrefix}{call};\n            global::AvtoBus.Handlers.HandlerResult.Apply(ctx, __result);",
            ReturnKind.SyncValue => $"var __result = {call};\n            global::AvtoBus.Handlers.HandlerResult.Apply(ctx, __result);",
            _ => $"{call};",
        };

        if (h.IsAsync && h.ReturnKind is ReturnKind.Void)
            body = $"await System.Threading.Tasks.Task.CompletedTask;\n            {call};";

        var handlerResolution = isInstance
            ? $"var __handler = ctx.Services.GetRequiredService<{h.ContainingType}>();\n            "
            : "";

        var source = $$"""
            // <auto-generated/>
            #nullable enable
            using System;
            using System.Threading.Tasks;
            using Microsoft.Extensions.DependencyInjection;

            namespace AvtoBus.Generated;

            internal sealed class {{className}} : {{DispatcherInterface}}
            {
                public global::System.Type MessageType => typeof({{fullQualifiedMsgType}});

                public string HandlerName => "{{h.HandlerName}}";

                public async global::System.Threading.Tasks.ValueTask DispatchAsync(global::AvtoBus.ConsumeContext ctx)
                {
                    var __msg = ({{fullQualifiedMsgType}})ctx.Message;
                    {{handlerResolution}}{{dependencyLines}}
                    {{body}}
                }
            }
            """;

        spc.AddSource($"{className}.g.cs", source);
    }

    public static void EmitInterfaceDispatcher(SourceProductionContext spc, InterfaceConsumerInfo c, Compilation compilation)
    {
        var className = ClassNameFor(c.HandlerType, c.MessageClrType);
        var contextType = $"global::AvtoBus.ConsumeContext<{c.MessageClrType}>";

        var source = $$"""
            // <auto-generated/>
            #nullable enable
            using System;
            using System.Threading.Tasks;
            using Microsoft.Extensions.DependencyInjection;

            namespace AvtoBus.Generated;

            internal sealed class {{className}} : {{DispatcherInterface}}
            {
                public global::System.Type MessageType => typeof({{c.MessageClrType}});

                public string HandlerName => "{{c.HandlerName}}";

                public async global::System.Threading.Tasks.ValueTask DispatchAsync(global::AvtoBus.ConsumeContext ctx)
                {
                    var __handler = ctx.Services.GetRequiredService<{{c.HandlerType}}>();
                    var __typed = ({{contextType}})ctx;
                    await __handler.ConsumeAsync(__typed);
                }
            }
            """;

        spc.AddSource($"{className}.g.cs", source);
    }

    private static string BuildCall(HandlerInfo h, bool isInstance)
    {
        var receiver = isInstance ? "__handler" : h.ContainingType;
        var args = new System.Collections.Generic.List<string>
        {
            $"({h.MessageClrType})__msg",
        };

        foreach (var dep in h.Dependencies)
        {
            args.Add($"__d_{dep.ParamName}");
        }

        return $"{receiver}.{h.MethodName}({string.Join(", ", args)})";
    }

    public static void EmitRegistration(
        SourceProductionContext spc,
        ImmutableArray<HandlerInfo> methods,
        ImmutableArray<InterfaceConsumerInfo> interfaces)
    {
        if (methods.Length == 0 && interfaces.Length == 0)
            return;

        var builder = new StringBuilder();
        foreach (var h in methods)
        {
            builder.AppendLine($"        AvtoBusRegistry.Register(typeof({h.ContainingType}), new {ClassNameFor(h.ContainingType, h.MessageClrType)}());");
        }

        foreach (var c in interfaces)
        {
            builder.AppendLine($"        AvtoBusRegistry.Register(typeof({c.HandlerType}), new {ClassNameFor(c.HandlerType, c.MessageClrType)}());");
        }

        var source = $$"""
            // <auto-generated/>
            #nullable enable
            using System.Runtime.CompilerServices;
            using AvtoBus.Dispatching;

            namespace AvtoBus.Generated;

            internal static class AvtoBusModuleInit
            {
                [ModuleInitializer]
                internal static void Init()
                {
            {{builder}}
                }
            }
            """;

        spc.AddSource("AvtoBusModuleInit.g.cs", source);
    }

    private static string ClassNameFor(string containingType, string messageType)
    {
        var type = messageType.Split('.').Last().TrimEnd('?');
        var name = containingType.Split('.').Last() + "_" + type + "_Dispatcher";
        return Sanitize(name);
    }

    private static string Sanitize(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var ch in value)
        {
            if (char.IsLetterOrDigit(ch) || ch == '_')
                builder.Append(ch);
            else
                builder.Append('_');
        }

        return builder.ToString();
    }
}
