<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>AvtoBus integration for .NET Aspire AppHost.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

</Project>